### ISSUE TITLE
Key Vault Secrets Error

### ISSUE THREAD

**Issue by thepaulmacca** [Azure/AppConfiguration-KubernetesProvider#18]
When I'm applying key vault secrets (based off the docs example [here](https://learn.microsoft.com/en-gb/azure/azure-app-configuration/use-key-vault-references-dotnet-core) I'm getting the below error:

```go
W0304 14:14:08.310104       1 appconfigurationprovider_controller.go:261] Fail to update the target ConfigMap or Secret of AzureAppConfigurationProvider 'appconfigurationprovider-example' in 'testing' namespace: Secret "secret-created-by-appconfig-provider" is invalid: data[TestApp:Settings:KeyVaultMessage]: Invalid value: "TestApp:Settings:KeyVaultMessage": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

Here is my JSON file if it helps

```json
{
  "Settings:KeyVaultMessage": {"uri":"https://<redacted>.vault.azure.net/secrets/Message"}
}
```

Is it worth mentioning this in the provider docs? Normal key/values are working fine btw

Thanks

**Comment by thepaulmacca** [comment]
Do you think it's worth adding something to the docs about this, with suggested examples?

**Comment by RichardChen820** [comment]
I was thinking we probably could have a TSG for the Kubernetes Provider, list the frequently encountered error messages, explain more in detail, and give guides to address them.

**Comment by zhenlan** [comment]
We should try to have error messages self-explanatory as much as possble. I hope most users don't even need to look for documentation. For example, the message in this current one can be improved. But I agree to include those trickier ones that need more explanation in the troubleshooting document.

https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-azure-kubernetes-service#troubleshooting

**Comment by thepaulmacca** [comment]
That would be good, thanks. I've been following the docs mostly up to this point, but it's clear some things work a bit differently when using the K8s provider

**Comment by thepaulmacca** [comment]
For some bizarre reason this looks to be working today, with my JSON file above

![image](https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/41340540/e31db604-b53e-4a73-936f-724168921d9d)

I'll close this issue now, thanks

**Comment by vaganovk** [comment]
Faced same issue, where secrets defined in App Configuration in hierarchical format with colon as separator (e.g. "Section:SecretName") cannot be handled by AKS App Configuration provider. 

Is there any workaround except to rename all App Configuration keys (both settings and secrets - as we want to keep related configuration grouped)? We are currently consuming same App Configuration by .NET services directly and ":" is convenient delimiter to stay with. 

Are there any other workarounds? 

The improvement https://github.com/Azure/AppConfiguration/issues/870 seem to be addressing this limitation, but details and timeline is not clear.

From C# perspective there might be simpler solutions:
1. OK to have separate config maps for settings and secrets, as one can easily join them via configBuider.AddJsonFile()
2. OK to keep secrets in current format as one can add them via configBuilder.AddIniFile() or alike. 
3. But no support for ":" in secret name seem to be a major blocker which requires each k8s pod to read configuration independently. 

If the improvement https://github.com/Azure/AppConfiguration/issues/870 takes long to implement, does it make sense to introduce simple replacer for e.g. ":" to "__" in AKS provider for secret names? This way "Section:SecretName" becomes "Section__SecretName" in k8s secret which is easier to consume (Injected as pod env variable, or read by custom Configuration Provider with "__" replaced back to ":" as environment vars provider in .NET does?)
