### ISSUE TITLE
Is there other way install App Configuration Kubernetes Provider besides helm

### ISSUE THREAD

**Issue by scorpionfly7** [Azure/AppConfiguration-KubernetesProvider#21]
Hi,
Is there posibillity add App Configuration Kubernetes Provider like add-on in cluster? does it have all features as helm installed?

BR

**Comment by RichardChen820** [comment]
It will be an extension of [AKS](https://learn.microsoft.com/en-us/azure/aks/cluster-extensions) or Arc-enabled cluster. We are working with AKS team on this. Please stay tuned.

**Comment by scorpionfly7** [comment]
Hello, when is planned to have it?

**Comment by RichardChen820** [comment]
We are working on the release, it's going out soon.

**Comment by RichardChen820** [comment]
The Azure App Configuration extension for AKS is in public preview.
https://azure.microsoft.com/en-us/updates/appconfig-aksextension/

**Comment by RichardChen820** [comment]
@scorpionfly7 The Azure App Configuration extension for AKS is general available now.
