### ISSUE TITLE
exec /manager: exec format error

### ISSUE THREAD

**Issue by scorpionfly7** [Azure/AppConfiguration-KubernetesProvider#25]
When installing with helm
helm install azureappconfiguration.kubernetesprovider
oci://mcr.microsoft.com/azure-app-configuration/helmchart/kubernetes-provider
--namespace azappconfig-system
--create-namespace

and deploying

apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
name: appconfigurationprovider-sample
spec:
endpoint:
target:
configMapName: configmap-created-by-appconfig-provider
configMapData:
type: json
key: mysettings.json
auth:
workloadIdentity:
managedIdentityClientId:

There is error in pod exec /manager: exec format error Why it happening?

**Comment by linglingye001** [comment]
This issue is tracked in [Azure/AppConfiguration/issues/892](https://github.com/Azure/AppConfiguration/issues/892).
