### ISSUE TITLE
Support LoadBalance mode

### ISSUE THREAD

**Issue by RichardChen820** [Azure/AppConfiguration-KubernetesProvider#55]
Support load balance according to what proposed in https://github.com/Azure/AppConfiguration/issues/868

**Comment by linglingye001** [comment]
It's supported in version `2.1.0`

**Comment by zhenlan** [comment]
@linglingye001 please update the document
https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-geo-replication?tabs=kubernetes#load-balance-with-replicas
