### ISSUE TITLE
namespace for generated configMap

### ISSUE THREAD

**Issue by spintower** [Azure/AppConfiguration-KubernetesProvider#61]
The provider seems to always put the generated confgiMap into the `default` namespace. There is a setting in the `target` section to control the name of the configMap, but not its location. How can I create a confgMap in a different namespace?

**Comment by spintower** [comment]
Looks like namespace is set when creating the resource.

**Comment by RichardChen820** [comment]
Correct, the target ConfigMap is in the namespace of the AzureAppConfigurationProvider resource.
